version: '3.8'

services:
  mysqldb_car_selling:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=car
      - MYSQL_USER=car
      - MYSQL_PASSWORD=car
    ports:
      - '3306:3306'
    volumes:
      - mysql_car_selling:/var/lib/mysql
  car_selling:
    depends_on:
      - mysqldb_car_selling
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    command: bash -c "npm install && npm run start"
  adminer:
    image: adminer
    depends_on:
      - mysqldb_car_selling
    restart: always
    ports:
      - '8080:8080'

volumes:
  mysql_car_selling:
  node_modules:
